### ISSUE TITLE
ws.colissimo.fr/pudo-fo-frame/storeCallAndCheck.do... Failed to load resource

### ISSUE THREAD

**Issue by maximelebreton** [quadra-informatique/SoColissimo-Prestashop#11]
Bonjour,
je suis confronté à un problème récurrent.
Lors du process de commande, lorsque l'on est redirigés vers l'url so colissimo, cette erreur apparait :

```
http://ws.colissimo.fr/pudo-fo-frame/storeCallAndCheck.do;jsessionid=38E2791C37CF590F7C6ED56918A419DA.tc-shippingwebclp-NODEV1? Failed to load resource: the server responded with a status of 404 (Introuvable)
```
![image](https://cloud.githubusercontent.com/assets/1072425/10489977/38463bfc-729f-11e5-8683-f80cbaa7a5eb.png)

puis parfois c'est un message "votre session a expiré".
![image](https://cloud.githubusercontent.com/assets/1072425/10490720/d12bc7e4-72a2-11e5-9ec5-c7f86a2659bd.png)

Je ne comprends pas car cela arrive même lorsque je rafraîchis la page, et lorsque je reprends une commande du début (donc la session ne devrait pas avoir le temps d'expirer...)

Avez vous une idée du problème  ?

Merci !

**Comment by quadrateam** [comment]
Bonjour,

Depuis debut octobre 2015, la poste a fait des modifications sur son API, notamment un changement au niveau du parametrage. Nous avons eu plusieurs clients avec ce souci et avons fait une remontée du problème à la poste. Le problème se situant sur l'API et non au niveau du module. La poste nous a informé que depuis le 13 octobre le problème est résolu. Nos clients nous ont confirmé le retour à la normale.

Avez vous eu ce problème depuis le 13 ? Si oui pouvez vous nous communiquer votre adresse url de boutique afin que nous les prevenions ?

Cordialement,

**Comment by maximelebreton** [comment]
et bien à vrai dire, le problème est devenu récurrent depuis quelques jours, et cela semble coller avec la date du 13 octobre... donc de mon côté, il semble que ça ait eu l'effet inverse !

je vous communique les infos prochainement. merci !

**Comment by maximelebreton** [comment]
l'adresse concernée est comptoir-des-savonniers.com

**Comment by quadrateam** [comment]
Un incident a été ouvert à la Poste concernant votre problème, nous vous tiendrons informé.

**Comment by maximelebreton** [comment]
bonjour, pouvez vous m'indiquer les coordonnées du service de la poste concerné,
car durant le week end nous avons enregistré un nombre inhabituel et considérable de paniers abandonnés, ce qui ne peut être causé que par cela !
Et considérant cela comme un bug à haute priorité, j'aimerais m'assurer que La Poste considère bien le caractère **URGENT** du problème.

**Comment by sylvaincha** [comment]
Bonjour @maximelebreton @quadrateam j'ai le même soucis, avez vous trouvé une solution? workout?

Merci d'avance pour votre réponse,

Sylvain

**Comment by bdecarne** [comment]
Bonjour,

Ce problème est grave car le nombre de paniers abandonnés devient alarmant. Il faut relancer La Poste sur le sujet et insister sur le caractère URGENT de la situation.

**Comment by sylvaincha** [comment]
@bdecarne je viens d'appeler le support technique de la poste, ils m'indiquent que le probléme viens du module et pas de l'api... (normal) ils travaillent dessus, je vous tiens informé...

**Comment by maximelebreton** [comment]
j'ai eu josselin du service technique de la poste qui n'arrive pas à reproduire le problème, donc je vais essayer de poster ici un max d'infos. @sylvaincha je t'invite à faire de même.
@quadrateam qui avez vous contacté au sein de la poste ?

**Comment by sylvaincha** [comment]
De mon côté, le bug à disparu...

**Comment by maximelebreton** [comment]
**23/10/2015**
```windows 7, chrome 46```
14h54 - je m'apprête à passer commande
----
![image](https://cloud.githubusercontent.com/assets/1072425/10693563/56bb31a4-7999-11e5-81ec-f2353164d118.png)

  
14h55 - j'appuie sur commander : page blanche
---
première étape de la livraison so colissimo (redirection vers ws.colissimo.fr)
page blanche, pas d'erreur console
```
http://ws.colissimo.fr/pudo-fo-frame/storeCallAndCheck.do;jsessionid=8612988A6CAA6591EA95D3FCCEF3A211.tc-shippingwebclp-NODEV2?
```
![image](https://cloud.githubusercontent.com/assets/1072425/10693247/4b8d9ae4-7997-11e5-9b2c-e1f8d6106c00.png)

**15h00 - refresh de l'étape 1 : ça marche**
----
url:
```
http://ws.colissimo.fr/pudo-fo-frame/storeCallAndCheck.do;jsessionid=8612988A6CAA6591EA95D3FCCEF3A211.tc-shippingwebclp-NODEV2?
```

cookie : 
```
JSESSIONID	8612988A6CAA6591EA95D3FCCEF3A211.tc-shippingwebclp-NODEV2	ws.colissimo.fr	/	Session	67				
point_retrait	0|350520|R01|fr_FR	ws.colissimo.fr	/pudo-fo-frame	2083-11-09T19:52:04.066Z	31				
xtan	-467706	.ws.colissimo.fr	/	2016-10-22T12:54:21.000Z	11				
xtant	1	.ws.colissimo.fr	/	2016-10-22T12:54:21.000Z	6				
xtvrn	$467706$	.ws.colissimo.fr	/	2016-10-18T11:45:47.000Z	13				
```
  
15h05 : passage à l'étape 2 : session expirée
-------
```
JSESSIONID	8612988A6CAA6591EA95D3FCCEF3A211.tc-shippingwebclp-NODEV2	ws.colissimo.fr	/	Session	67				
point_retrait	0|350520|R01|fr_FR	ws.colissimo.fr	/pudo-fo-frame	2083-11-09T19:52:04.066Z	31				
xtan	-467706	.ws.colissimo.fr	/	2016-10-22T12:54:21.000Z	11				
xtant	1	.ws.colissimo.fr	/	2016-10-22T12:54:21.000Z	6				
xtvrn	$467706$	.ws.colissimo.fr	/	2016-10-18T11:45:47.000Z	13				
```

  
15h15 - je vide mes cookies, et je recommence à zéro.
---------

**cette fois, pour toutes les étapes ça fonctionne**

cookie:
```
JSESSIONID	2FFF4CE2F702EE57DA437A2C8312235B.tc-shippingwebclp-NODEV5	ws.colissimo.fr	/	Session	67				
point_retrait	"1| | |fr_FR"	ws.colissimo.fr	/pudo-fo-frame	2083-11-10T16:34:25.477Z	26				
xtan	-467706	.ws.colissimo.fr	/	2016-10-22T13:20:43.000Z	11				
xtant	1	.ws.colissimo.fr	/	2016-10-22T13:20:43.000Z	6				
xtvrn	$467706$	.ws.colissimo.fr	/	2016-10-22T13:19:09.000Z	13				
```

une différence au niveau du cookie : NODEV2 > NODEV5

coup de bol ?
----
je reteste pour voir si cela se reproduit.


15h32 : re-vidage de cookies, re-test, tout est ok
----
cookie
```
JSESSIONID	B7A12EB528DCE8DC97DCDBF501B09660.tc-shippingwebclp-NODEV2	ws.colissimo.fr	/	Session	67				
xtan	-467706	.ws.colissimo.fr	/	2016-10-22T13:31:39.000Z	11				
xtant	1	.ws.colissimo.fr	/	2016-10-22T13:31:39.000Z	6				
xtvrn	$467706$	.ws.colissimo.fr	/	2016-10-22T13:31:39.000Z	13				
```

à suivre...
-----
je continue mes tests dans la journée.

**Comment by Haratryn** [comment]
Bonjour,

Je rencontre aussi le problème et je n'arrive pas à trouver de solution et à avoir de retour de la part de mon prestataire.

Auriez-vous trouvé une solution?

J'ai pu constater que sur www.comptoir-des-savonniers.com vous n'utilisiez plus d'iframe. Est-ce la solution pour résoudre ce problème?

Cordialement,

**Comment by sylvaincha** [comment]
@Haratryn Bonjour,

Suivez les étapes recommandées par @maximelebreton et retestez votre site depuis un autre navigateur ET une page de navigation privée

**Comment by cleroy33** [comment]
Bonjour,
En vidant mes cookies je n'ai effectivement plus ce problème, mais la plupart de mes clients sont totalement incapables de la faire et continuent donc à avoir ce problème.
Comment faire pour que ce soit résolu également de leur côté ?

Merci

**Comment by Haratryn** [comment]
Bonjour,

Pour ma part, j'ai contacté So Colissimo afin de les informer du problème et après recherche, ils ont identifié un défaut de configuration sur l'un de leurs serveurs.

Le problème devrait être résolu désormais.

**Comment by ptosent** [comment]
Bonjour, 

Nous avons ce problème pour le site http://www.kosmosparis.fr/, pouvez-vous prévenir la Poste ? 

Merci d'avance.

**Comment by quadrateam** [comment]
Bonjour,

Pour information, la poste vas procéder à une maintenance de leurs infrastructure la nuit du samedi 23 au dimanche 24 Janvier.

A voir si cela améliore ce point.

**Comment by bdecarne** [comment]
Ou pas.

**Comment by Ledfanatic** [comment]
Bonjour,

En cours de test sur Prestashop 1.6.1.4, je rencontre exactement les mêmes problèmes que cités plus haut, à savoir : Page banche, session expirée ou lorsque cela arrive à aller plus loin "Error occurred during shipping step." au retour de l'Iframe...
J'hésite fortement à intégrer ce module à mon site web vu la quasi impossibilité de passer une commande..;mais peut-être que ce problème a été identifié et résolu ? Ou alors c'est mon installation qui n'est pas réglée comme il faut ?
J'ai déjà passé de nombreuses heures et je ne vois pas de remède même après effacement des différents caches et suppression des cookies...
Je suis quand même arrivé à passer 2 ou 3 commandes sur 25 ou 30 tests. Ce qui prouve quand même que le système pourrait fonctionner.

Merci d'avance de vos lumières.

**Comment by sylvaincha** [comment]
Bonjour,

Suis la procédure indiquée dans les messages précédents et ça va le faire, une fois mis en place le module est stable...

Variante, essaye depuis un autre ordinateur...

Bon courage

Sylvain

Le 5 févr. 2016 10:41 PM, Ledfanatic <notifications@github.com> a écrit :
Bonjour,

En cours de test sur Prestashop 1.6.1.4, je rencontre exactement les mêmes problèmes que cités plus haut, à savoir : Page banche, session expirée ou lorsque cela arrive à aller plus loin "Error occurred during shipping step." au retour de l'Iframe...
J'hésite fortement à intégrer ce module à mon site web vu la quasi impossibilité de passer une commande..;mais peut-être que ce problème a été identifié et résolu ? Ou alors c'est mon installation qui n'est pas réglée comme il faut ?
J'ai déjà passé de nombreuses heures et je ne vois pas de remède même après effacement des différents caches et suppression des cookies...
Je suis quand même arrivé à passer 2 ou 3 commandes sur 25 ou 30 tests. Ce qui prouve quand même que le système pourrait fonctionner.

Merci d'avance de vos lumières.

---

**Comment by Ledfanatic** [comment]
Merci sylvain pour ta réponse...
Du courage je n'en manque pas mais là je suis un peu dépité....
J'ai bien entendu suivi la procédure, essayé à partir d'un autre ordinateur..etc..etc...

J'arrive effectivement à aller plus loin, mais en regardant mes logs apache de connexion (acces.log) je constate que toutes les commandes qui sont en échec  "Error occurred during shipping step." au retour de l'Iframe, ont la variable orderID=0008 ???? alors que les commandes qui passent on bien la varaible orderID qui correspond au numéro de commande (3545 par exemple).

On dirait que le module n'envoi pas le serial orderID correctement mais ou va-t-il prendre ce 0008 ?

Je ne comprends plus rien....mais merci encore pour ton soutien.

**Comment by sylvaincha** [comment]
Tu as essayé de desinstaller réinstaller le module ?

Sinon, y'a une assistance technique chez colissimo, faut avoir un contrat avec eux et tu peux les contacter...

Le 5 févr. 2016 11:14 PM, Ledfanatic <notifications@github.com> a écrit :
Merci sylvain pour ta réponse...
Du courage je n'en manque pas mais là je suis un peu dépité....
J'ai bien entendu suivi la procédure, essayé à partir d'un autre ordinateur..etc..etc...

J'arrive effectivement à aller plus loin, mais en regardant mes logs apache de connexion (acces.log) je constate que toutes les commandes qui sont en échec  "Error occurred during shipping step." au retour de l'Iframe, ont la variable orderID=0008 ???? alors que les commandes qui passent on bien la varaible orderID qui correspond au numéro de commande (3545 par exemple).

On dirait que le module n'envoi pas le serial orderID correctement mais ou va-t-il prendre ce 0008 ?

Je ne comprends plus rien....mais merci encore pour ton soutien.


---

**Comment by Ledfanatic** [comment]
J'ai désinstallé le module plusieurs fois, et réinstallé...

Actuellement toutes les commandes "à domicile" semblent passer. Par contre impossible de valider une commande en Point Relais...j'ai toujours l'erreur "Error occurred during shipping step." en retour de l'iframe...mais tout se passe correctement dans l'Iframe...

Donc j'ai un deuxième problème ailleurs et je vais arrêter de polluer ce fil.

Et oui j'ai un compte Client Colissimo, je verrai ça lundi.

Merci  et bon weekend !

**Comment by quadrateam** [comment]
Bonjour,

Ce probleme est du a un bug de la plateforme de la poste dans le recalcul de clé de securité.

Le parametrage de calcul renvoyé par l'api de la poste n'est pas le bon.

Nous sommes en relation avec la poste pour la resolution du problème.

Pour l'instant il ne faut pas remplir le champ tarif de livraison en bureau de poste dans votre espace colisposte. Laissez le à blanc.

Cela resoudra le problème.

cordialement,

**Comment by sylvaincha** [comment]
Bonjour,

Merci pour cette information, cela signifie t-il que même les installations fonctionnelles sont bugées ?

Le 8 févr. 2016 4:43 PM, Quadra Informatique <notifications@github.com> a écrit :
Bonjour,

Ce probleme est du a un bug de la plateforme de la poste dans le recalcul de clé de securité.

Le parametrage de calcul renvoyé par l'api de la poste n'est pas le bon.

Nous sommes en relation avec la poste pour la resolution du problème.

Pour l'instant il ne faut pas remplir le champ tarif de livraison en bureau de poste dans votre espace colisposte. Laissez le à blanc.

Cela resoudra le problème.

cordialement,

---

**Comment by quadrateam** [comment]
Bonjour,

Non , cela fonctionne si vous ne touchez pas au tarif bureau de poste dans la configuration du compte colisposte.

Pour faire simple une fois que vous activez ce parametre sur votre compte colisposte, au moment du retour de votre choix d'adresse dans votre tunnel d'achat, la clé de securité ne sera plus correcte et donc erreur.

Le parametrage renvoyé par l'api de la poste est different de celui qu'elle a utilisé pour calculer la clé de securité, il est donc impossible coté boutique de recalculer la bonne clé.

En n'utilisant pas ce parametre vous n'aurez donc pas d'erreur. N'ayant pas la main sur l'api de la poste nous ne pouvons rien faire pour le moment.

Une fois corrigé, nous implémenterons cette notion tarifaire dans une nouvelle version du module.

Bien cordialement,

**Comment by Ledfanatic** [comment]
Bonjour @quadrateam @sylvaincha ,

Tout d'abord merci pour votre réponse qui me rassure un peu sur ma problématique. Merci également de m'avoir répondu par email :)

Avec un sniffer nous sommes arrivés effectivement à la conclusion que le problème venait de la signature qui n'était pas cohérente entre celle renvoyée par la Poste et celle calculée par le module Colissimo.
Nous allons essayer votre préconisation de mettre le champ tarif en bureau de poste à blanc et nous vous tiendrons au courant du résultat.

Bonne journée.

**Comment by Ledfanatic** [comment]
Et donc....je confirme, cette fois cela fonctionne....dommage que nous ayons perdu autant de temps à identifier le problème, mais l'important c'est d'avoir trouvé une réponse satisfaisante :)

**Comment by maximelebreton** [comment]
https://github.com/quadra-informatique/SoColissimo-Prestashop/issues/11#issuecomment-181257606
merci @quadrateam.
il aura donc fallu 4 mois à La Poste pour identifier un bug de cette priorité, est-ce qu'il faut rire ou pleurer ?
(j'attends la correction et confirmation de tout de le monde avant de fermer l'issue)

**Comment by lupillus** [comment]
Hello all,

I'm sorry I don't speak French, but If any one can explain what should I do to fix this issue (even temporary). I have used google translate to understand what was written above, but I don't understand where is this:
le champ tarif de livraison en bureau de poste dans votre espace colisposte. Laissez le à blanc.

Is it in module settings, or in prestashop carrier administration, or somewhere else.

Thank you very much!

**Comment by quadrateam** [comment]
Hi,

It is not in your prestashop site, it is in your colisposte administration.

Regards,

**Comment by lupillus** [comment]
Thank you for your answer @quadrateam
