### ISSUE TITLE
bug commande non enregistrée correctement si parenthèses dans nom du relais

### ISSUE THREAD

**Issue by mockassin** [quadra-informatique/SoColissimo-Prestashop#13]
bonjour, 
s'il y a des parentheses dans le nom du relais qui est retourné par le serveur colissimo, ca bug.
solution ici: https://www.prestashop.com/forums/topic/500961-bugs-socolissimo-simplicit%C3%A9-2016/

**Comment by quadrateam** [comment]
Bonjour,

Merci pour votre retour, nous allons etudier ce bug et inclure sa correction dans la prochaine version du module.

Cordialement,

**Comment by quadrateam** [comment]
Bonjour,

La version 2.10 du module a été publiée ce jour.

Cordialement,
