### ISSUE TITLE
Impossible d'utiliser So Colissimo Simplicité Iframe si le module Conformité européenne améliorée est activé.

### ISSUE THREAD

**Issue by Ledfanatic** [quadra-informatique/SoColissimo-Prestashop#14]
Bonjour,
Je viens de m'apercevoir que l'option "Iframe" ne fonctionne plus, on arrive directement sur la page de paiement après une ouverture furtive de la page web de colissimo et une fermeture sans action de notre part ??

En recherchant les modifications apportées à ma configuration j'ai identifié que j'avais installé le module "conformité européenne améliorée" depuis mes tests ou tout fonctionnait bien.

Ce soir je viens de désactiver ce module et il semble que la connexion à colissimo dans une Iframe fonctionne à nouveau. 
Pour en être certain j'ai réactivé le module "conformité européenne améliorée" et bingo j'ai de nouveau le bug...

Pourriez-vous investiguer sur ce dysfonctionnement ? J'ai mis  en mode Fancy box pour le moment sur mon site car je souhaite conserver la fonctionnalité du module "conformité européenne amélioré"

Merci d'avance.

Prestashop 1.6.1.4 - Conformité Européenne Améliorée V 2.0.1 - Colissimo simplicité V 2.9.24

**Comment by quadrateam** [comment]
Re Bonjour,

Je vous confirme que nous reproduisons le bug.

Nous allons voir pourquoi et vous tenons informé.

Cordialement,

**Comment by quadrateam** [comment]
Le problème a été identifié, il s'agit du script fo_aeuc_tnc.js du module conformité européenne qui prend le pas sur le script colissimo dans le cas d'iframe.

le code est le suivant : 
$('button[name="processCarrier"]').click(function(event){
        /* Avoid any further action */
        event.preventDefault();
        event.stopPropagation();

        if (aeuc_has_virtual_products === true && aeuc_controller.checkVirtualProductRevocation() === false)
        {
            var to_display = $('<div/>').html(aeuc_virt_prod_err_str).text();
            $.fancybox(to_display,{
                minWidth: 'auto',
                minHeight: 'auto'
            });
            return;
        }
        $("#form").submit();
    });
Nous allons remonter l'info a prestashop qui est le developpeur du module.

**Comment by Ledfanatic** [comment]
Bonjour,

Merci pour votre réactivité. Ca fait plaisir d'avoir du support en quasi temps réel.

ll ne reste donc plus qu'à attendre une mise à jour du module Conformité européenne pour pouvoir utiliser So Colissimo en iframe, mais là ça n'est plus de votre ressort et ça risque de prendre plus de temps ;)
Bonne fin de journée.

**Comment by quadrateam** [comment]
Re bonjour,

Nous avons mis en place un contournement pour pallier au problème.
Cette modification est en recette chez nous et si les tests sont concluants nous l'incluerons dans la prochaine relaese du module.

Pour info : 

dans le dossier views/templates/front du module editer le fichier socolissimo_iframe.tpl

ligne 89 changer $('[name=processCarrier]').click(function () {

par $("#form").submit(function () {

Merci de votre retour.
Cordialement,

**Comment by Ledfanatic** [comment]
J'ai appliqué la modification sur ma version bac à sable...et effectivement l'Iframe est maintenant correcte. J'attends encore quelques tests et je passerai en production, je ne pense pas que cela puisse impacter autre chose, mais sait-on jamais.

Merci encore de votre réactivité sur cet incident.

Très sincèrement

**Comment by asmadr** [comment]
Bonjour,
J'ai un problèème avec le module. Il est installé sur la version 1.4 de préstashop . Les transporteur sont bien configuré et le tarifs selon le poids sont saisies en BO. Cependant le tarifs la poste est toujours celle de compte socolismo de client ca devrait être selon le poids de panier mais ca change pas. J'ai fait d'autre tests sur autres version de prestashop et le module fonctionne correctement. Pouvez-vous m'aider pour résoudre ce problème ?

**Comment by asmadr** [comment]
Toujours pas de réponse. C'est un problème de module ou bien au niveau de paramétrage de compte client?
Merci par avance!!

**Comment by quadrateam** [comment]
@asmadr 

Merci de ne pas mélanger les sujets svp.
Le ticket parle du problème de compatibilité avec le module Conformité européenne.

Si vous avez un problème autre que celui ci veuillez svp nous contactez via addons.
Le problème de compatibilité étant résolu, je clos ce ticket.

Merci de votre compréhension
cordialement,
