### ISSUE TITLE
Bug d'affichage Module Colissimo Simplicité et Safari OSX

### ISSUE THREAD

**Issue by adrien56** [quadra-informatique/SoColissimo-Prestashop#15]
Bonjour,

 J'ai actuellement un bug avec mon module Colissimo Simplicité.
Lorsque l'on utilise le navigateur Safari sous Mac (OSX), on obtient l'erreur suivante:

_Etat HTTP 500 - java.lang.NullPointerException_

Et cela à l'étape 4 / Frais de port, à l'affichage du module Colissimo ?

Merci d'avance

**Comment by quadrateam** [comment]
Bonjour,

Le souci vient de l'api de la poste.

Un incident a été ouvert hier au service technique de la poste.

Sa résolution est en cours.

Cordialement

**Comment by okom3pom** [comment]
Si vous attendez après Colisposte c'est pas gagné ! 

Vous pouvez ajouter une méthode à la class Socolissimo

`	public function isMobile()
	{
		
		if(strpos( $_SERVER['HTTP_USER_AGENT'], 'Safari') !== false)
			return true;
		else  if(  method_exists(Context::getContext()->mobile_detect,isMobile)  )
			return Context::getContext()->mobile_detect->isMobile();
		else
			return false;
		
	}`

Et ajouter 2 fois 

`|| $this->isMobile()`

Après 

`$this->isIpad`

Du coup le navigateur safari est redirigé sur la page mobile sans erreur

**Comment by doekia** [comment]
On parle de cette erreur là?

```
Etat HTTP 500 _ Java.lang.null pointer exception
type Rapport d''exception message java.lang.NullPointerException
description Le serveur a rencontré une erreur interne qui l''a empêché de satisfaire la requête.

exception

javax.servlet.ServletException: java.lang.NullPointerException
	org.apache.struts.action.RequestProcessor.processException(RequestProcessor.java:535)
	org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:433)
	org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:236)
	org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
	org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	com.geopost.pudofo.fwk.TimeoutFilter.doFilter(TimeoutFilter.java:85)
	com.geopost.pudofo.fwk.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:196)

cause mère

java.lang.NullPointerException
	com.geopost.pudofo.page.action.StoreCallAction.doExecute(StoreCallAction.java:156)
	com.geopost.pudofo.page.action.PudoFOAction.execute(PudoFOAction.java:40)
	org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431)
	org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:236)
	org.apache.struts.action.ActionServlet.process(ActionServlet.java:1196)
	org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	com.geopost.pudofo.fwk.TimeoutFilter.doFilter(TimeoutFilter.java:85)
	com.geopost.pudofo.fwk.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:196)

note La trace complète de la cause mère de cette erreur est disponible dans les fichiers journaux de Apache Tomcat/7.0.63.
```

Parce que j'ai eu plusieurs client avec ce problème, ni sous mac, ni sous safari, ... pas mal de windows10 par contre et edge/chrome/firefox pareil

La cause semble être liée au jeu de caractère +/- forcé:configuré chez l'internaute et l'incapacité du serveur Tomcat à convertir de l'utf-8 en iso8859-1

Bug rapporté plusieurs fois à La Poste pour l'instant sans résolution.

**Comment by okom3pom** [comment]
Ouin, du coup doekia, tu peux en attendant retourner true à isMobile comme ça tous les navigateurs iront sur la page mobile sans erreur.

En plus je la trouve mieux :)

**Comment by okom3pom** [comment]
A noter que Chrome aussi est redirigé vu son USER_AGENT

**Comment by quadrateam** [comment]
@okom3pom  ,

Nous avons mergé votre code et procédons a des tests de retro compat sur les versions anterieures.

@doekia, @adrien56 
la résolution de ce bug est prévue au 8 avril par la poste.

**Comment by okom3pom** [comment]
@quadrateam ok, rediriger les navigateurs sur la page mobile est une bonne solution en attendant le 8 avril

Pour le PR j'ai testé 1.5 et 1.6 mais pas en 1.4

**Comment by adrien56** [comment]
Merci pour vos retours !

**Comment by quadrateam** [comment]
Je cloture.

**Comment by okom3pom** [comment]
Dommage de fermer issue qui n'est pas résolu

**Comment by mockassin** [comment]
oui ce serait bien de confirmer quand cela sera résolu coté La Poste

**Comment by okom3pom** [comment]
Bon je suis désolé de vous informer que la poste à résolu le problème de la manière suivante : 

> Pour information nous avons mis en place une nouvelle version de la page simplicité. Cette version, dans le cas où les cookies ou cookies tiers  ne sont pas autorisés par le navigateur du client retourne une page indiquant qu'il est nécessaire d'activer les cookies pour pouvoir utiliser la page simplicité.

#commentperdredescommandes 

La page fonctionnait très bien avant je vois pas pourquoi elle ne fonctionne plus maintenant, ce message est le type d'erreur qui provoque un abondons de panier de 99%  

Franchement un scandale.

**Comment by mockassin** [comment]
oui c'est bien dommage. j'avais déja noté des problèmes avec les cookies de la poste. l'idéal serait de développer un module liberté par la poste qui permet de ne pas passer par l'iframe. car en effet l'iframe n'est pas du tout flexible et impose une ergonomie et des problèmes qui vont avec.
@quadrateam vous pensez que la poste accepterait que vous developpiez le module liberté si les clients le faisaient massivement auprès de la poste?

**Comment by mockassin** [comment]
par contre d'après la réponse de la poste, je ne comprends pas le rapport entre les cookies et la version mobile/ipad? cela voudrait il signifier que certains mobiles n'ont pas les cookies activés? est ce vraiment l'origine du problème?

**Comment by ChDUP** [comment]
pas vraiment.
Ça ressemble plutôt à du "on voit pas trop pourquoi, alors on va leur mettre un message d'erreur sur les cookies, vu que quand les cookies tiers sont autorisés, ça fonctionne".
Ce qui n'est vraiment satisfaisant.

**Comment by mockassin** [comment]
quelqu'un a réussi à répliquer le bug post "pseudo-correction" ?

**Comment by okom3pom** [comment]
oui désactive les cookies tiers :+1:
