### ISSUE TITLE
Problème avec le tarif La poste toujours celui de compte client dans socolisimo

### ISSUE THREAD

**Issue by asmadr** [quadra-informatique/SoColissimo-Prestashop#18]
Bonjour,
J'ai un problèème avec le module. Il est installé sur la version 1.4 de préstashop . Les transporteur sont bien configuré et le tarifs selon le poids sont saisies en BO. Cependant le tarifs la poste est toujours celle de compte socolismo de client ca devrait être selon le poids de panier mais ca change pas. J'ai fait d'autre tests sur autres version de prestashop et le module fonctionne correctement. Pouvez-vous m'aider pour résoudre ce problème ?

**Comment by quadrateam** [comment]
Bonjour,

Pourriez me donner un exemple, par exemple avec quelques screens de votre probleme svp ?

J'ai du mal a cerner ce que vous entendez par "Cependant le tarifs la poste est toujours celle de compte socolismo de client ".

Cordialement,

**Comment by asmadr** [comment]
Merci pour votre réponse.
Le tarif la poste qui s'affiche dans l'iframe ne change pas selon le poids de produits, ni l'adresse toujours celui de la configuration de compte so-colismo  (7.5) . Les autres tarifs "En relais Pickup / consigne Pickup Station" par exmples varient selon les tranches de poids saisies pour ce transporteur . Vous retrouvez ci-joints les captures d'écrans de mon compte pour la configration ![configurationsocolismo](https://cloud.githubusercontent.com/assets/543593/14319570/9d12500e-fc09-11e5-8389-ee3ffa35a76b.jpg) et l'iframe qui s'affiche lors de choix de transporteur ![iframe_laposte](https://cloud.githubusercontent.com/assets/543593/14319581/a2bffccc-fc09-11e5-83eb-1c8ec69efed6.jpg).

**Comment by quadrateam** [comment]
ok, 

Je comprends mieux.

Historiquement ce tarif "bureau de poste" a été ajouté au compte colisposte en debut d'année.

Jusqu'a présent il posait problème sur le module car l'api de la poste ne renvoyait plus les bons paramètres pour recalculer la clé de cryptage.

Il n'a donc pas été implementé dans le module pour l'instant et il fallait le laisser à blanc sur le compte colisposte afin de ne pas avoir d'erreur sur le module.
Un correctif coté poste a été fait il y a un semaine environ. Celui ci corrige le problème de clé.

Maintenant sur le fonctionnement, il propose un tarif unique si le commerçant le désire(en le renseignant) pour les livraisons en bureau de poste uniquement. Donc de ce fait si vous le renseignez, il prendra le pas sur vos tranches poids/prix si le client choisit une livraison en bureau de poste et sera donc invariable.

Cela répond il a votre question ?

cordialement,

**Comment by asmadr** [comment]
Bonjour,
J'ai les bonnes tarifs pour la poste. Merci pour votre réponse. 
Cordialemnt
