### ISSUE TITLE
2 boutons sauvegarder non 1 inutile

### ISSUE THREAD

**Issue by Shiryu75** [quadra-informatique/SoColissimo-Prestashop#19]
Je vous laisser regarder votre formulaire. On a, en bas de page, 2 bouton de submit et le 2eme, celui tout en bas, ne fait rien.

**Comment by okom3pom** [comment]
Oui j'ai le même problème.

**Comment by quadrateam** [comment]
Bonjour,

Nous supprimerons le bouton inutile lors de la prochaine version.

Merci pour votre retour.

Cordialement,

**Comment by quadrateam** [comment]
La version 2.10 du module a été publiée ce jour.
