### ISSUE TITLE
Configuration du module en ayant skip la popup

### ISSUE THREAD

**Issue by Shiryu75** [quadra-informatique/SoColissimo-Prestashop#20]
Lors du submit, le message d'erreur suivant apparait : 

Impossible de sauvegarder les paramètres tant que les informations complémentaires ne sont pas saisies (siret, téléphone,code postal)

**Comment by quadrateam** [comment]
Un correctif sera apporté lors de la prochaine mise à jour ( 2.9.26)

Attention ces informations(siret,etc..) restent obligatoires

**Comment by ladymaga** [comment]
Bonjour, 
J'ai des soucis avec le module so colissimo simplicity. Il m'apparait également Impossible de sauvegarder les paramètres tant que les informations complémentaires ne sont pas saisies (siret, téléphone,code postal). Où dois -je rentrer ces infos (siret, etc...)
Merci.

**Comment by quadrateam** [comment]
Bonjour,

la version 2.10 publiée réaffiche le formulaire si le siret n'a pas été saisis;

si vous avez une version antérieur, il suffit de retourner sur la page de gestion des modules, d'aller sur le module Colissimo simplicité , et la popup est alors affichée.

**Comment by ladymaga** [comment]
Quand j'y retourne il n'apparait rien sur le siret etc.. dans la popup....

**Comment by quadrateam** [comment]
Bonjour,

Tout les champs du formulaire de la popup sont obligatoires, afin de pouvoir utiliser le module.

Cordialement

**Comment by ladymaga** [comment]
Mais moi je veux bien remplir tous les champs du formulaire. Sauf qu'il n'y en n'a pas. Comment le faire apparaître ce fameux formulaire ?
Moi je n'ai que les paramètres colissimo simplicité, url de retour, Paramètres Systèmes Colissimo Simplicité et Paramètres Systèmes PrestaShop. Mais aucun formulaire.
