### ISSUE TITLE
Le transporteur "La Poste - Commerce de proximité" ne marche pas

### ISSUE THREAD

**Issue by Shiryu75** [quadra-informatique/SoColissimo-Prestashop#21]
Tout est dans le titre ;)

En plus il est active = 0 de base. Donc afin d'éviter un malentendu avec les clients, il serait préférable de carrément retirer le bout de code qui crée ce transporteur.

Merci.

**Comment by quadrateam** [comment]
Bonjour,

Je pense qu'il y a incomprehension sur la fonction dont il fonctionne plutot.

En fait ce transporteur sert uniquement à avoir une grille tarifaire differente pour la livraison en commerce de proximité.

Exemple : vous créez une tranche de prix de 0 à 1000 euros. Sur le transporteur "normal" vous tarifez à 5 euros, et sur le transporteur "commerce de proximité" à 3 euros.

Avec cette configuration, vos clients dans la fenetre de choix d'adresse pourront avoir un tarif different selon le type de point retrait choisi. 3 euros pour les point commercant et 5 euros pour le reste.

Au dela de cette configuration (prestashop ne permettant pas de faire deux tarifications differentes par tranche) ce transporteur n'a pas vocation à être activé ou visible en front office.

Pour plus de détails n'hesitez pas a vous reporter à la documentation disponible ici .

http://shop.quadra-informatique.fr/fr/index.php?controller=attachment&id_attachment=17

Bien cordialement,
