### ISSUE TITLE
Variable prTown vide

### ISSUE THREAD

**Issue by okom3pom** [quadra-informatique/SoColissimo-Prestashop#22]
Bonjour,

Depuis jeudi, j'ai la variable prTown qui est vide sur la page mobile ?
Je sais que ce n'est pas vous mais avez-vous eux des infos à propos de ça ?

![so-prtown1](https://cloud.githubusercontent.com/assets/5064590/14596536/5b877d16-0547-11e6-990c-7d3261b78d2d.jpg)
![so-prtown2](https://cloud.githubusercontent.com/assets/5064590/14596537/5ba226b6-0547-11e6-8aff-40d50cef2919.jpg)

**Comment by ChDUP** [comment]
Même souci chez moi, qui provoque des erreurs de remontées des commandes ...

**Comment by quadrateam** [comment]
Bonjour,

Je viens également de reproduire le bug...

J’envoie une alerte au service technique de la poste.

Merci pour votre retour.

Cordialement,

**Comment by okom3pom** [comment]
Dire que je redirigeais tous les devices sur la page mobile pour corriger leur bug précédent, ils sont vraiment pas au top en ce moment !

Merci j'espère que votre remonté sera plus efficace que la mienne.

Actuellement je set la variable prTown avec comme valeur Ville pour résoudre le problème.

Vu que c'est du point relay ce n'est pas trop gênant.

**Comment by okom3pom** [comment]
C'est corrigé du côté de la poste.
