### ISSUE TITLE
Tarifs en bureau de Poste

### ISSUE THREAD

**Issue by fcdub** [quadra-informatique/SoColissimo-Prestashop#23]
Bonjour,
Depuis le 1er janvier la Poste facture le même tarif en bureau de Poste qu'en relais commerçant.
Avez-vous prévu de bientôt intégrer cette nouveauté ?

**Comment by quadrateam** [comment]
Bonjour,

La gestion du tarif en bureau de poste est disponible dans votre espace Colissimo Box.
Toute fois, un bug est ouvert auprès de la Poste, qui renvoie le tarif France au module.

Le traitement est en cours au niveau des équipes de la poste.
