### ISSUE TITLE
Does it use SOAP?

### ISSUE THREAD

**Issue by kagan94** [quadra-informatique/SoColissimo-Prestashop#24]
Hello, it's not an issue, but this is a question.

Does it use SOAP (in the back-end part) to check warehouses during the checkout process?
Because I intend to design a similar module for another system, that's why I'm asking this question.
Thanks in advance.

Kind regards,
Leonid Dashko

**Comment by quadrateam** [comment]
Hi,

The module does not deal with warehouses. Colissimo Simplicité is only a carrier.
The stock check is done internally by prestashop in the "add to cart" process.

Regards

**Comment by kagan94** [comment]
I think you do not understand my question.

I now that the stock checks internally, but I want to know how you estimate the cost of delivery. It should be an AJAX request, isn't it?

Thanks in advance.

**Comment by quadrateam** [comment]
No,

In the cart page, the price is calculated using the standard prestashop carrier price grid.

After, the formula where you choose the pickup station, is a call to a specific & external iframe provided by La Poste.

The iframe have it's own process which is external to Prestashop.

The prices display are also managed by an external webapp provided by La Poste to the merchant.

Regards.

**Comment by kagan94** [comment]
Thanks for a quick reply!

It seems that your module uses only fixed prices for calculating shipping costs, without calculating on the La Poste side. Am I right?

If not, how you can return calculated shipping price from the frame? I think it is impossible.
