### ISSUE TITLE
Page blanche commande via le backoffice

### ISSUE THREAD

**Issue by elito** [quadra-informatique/SoColissimo-Prestashop#25]
Lorsqu'on essaie de passer une commande via le backoffice on obtient cette erreur

Call to a member function getProducts() on null in /home/...../www/modules/socolissimo/socolissimo.php on line 1779

Nous venons de faire la mise à jour vers PS 1.6.1.7 et le module socolissimo est à jour également.

**Comment by quadrateam** [comment]
Bonjour,

Un fix vient d'etre envoyé, vous pouvez dès à présent le recupérer.
Nous publierons prochainement une nouvelle release incluant ce fix.

Merci pour votre retour.

Cdlt,

**Comment by elito** [comment]
Merci ! je salue la réactivité.
